version: '3.8'

services:
  vkquake-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: vkquake-server:latest
    container_name: vkquake-server
    
    # Run with custom user
    user: "${PUID:-1000}:${PGID:-1000}"
    
    # Network configuration
    ports:
      - "${QUAKE_PORT:-26000}:26000/udp"
    
    # Volume mounts
    volumes:
      - ${CONTAINER_DIR}/quake/game:/quake/game
      - ${CONTAINER_DIR}/quake/config:/quake/config
      - ${CONTAINER_DIR}/quake/logs:/quake/logs
    
    # Environment variables
    environment:
      # Server identification
      - QUAKE_SERVER_NAME=${QUAKE_SERVER_NAME:-vkQuake Docker Server}
      - QUAKE_MAX_PLAYERS=${QUAKE_MAX_PLAYERS:-16}
      - QUAKE_PORT=${QUAKE_PORT:-26000}
      
      # Game mode settings
      - QUAKE_DEATHMATCH=${QUAKE_DEATHMATCH:-1}
      - QUAKE_COOP=${QUAKE_COOP:-0}
      - QUAKE_TEAMPLAY=${QUAKE_TEAMPLAY:-0}
      - QUAKE_SKILL=${QUAKE_SKILL:-1}
      
      # Match settings
      - QUAKE_FRAGLIMIT=${QUAKE_FRAGLIMIT:-20}
      - QUAKE_TIMELIMIT=${QUAKE_TIMELIMIT:-15}
      
      # Map settings
      - QUAKE_MAP=${QUAKE_MAP:-start}
      - QUAKE_MAP_ROTATION=${QUAKE_MAP_ROTATION:-start,e1m1,e1m2,e1m3,e1m4,e1m5,e1m6,e1m7,e1m8}
      - QUAKE_ROTATION_MODE=${QUAKE_ROTATION_MODE:-1}
      
      # Admin settings
      - QUAKE_ADMIN_PASSWORD=${QUAKE_ADMIN_PASSWORD:-}
      
      # Bot settings
      - QUAKE_ENABLE_BOTS=${QUAKE_ENABLE_BOTS:-0}
      - QUAKE_BOT_COUNT=${QUAKE_BOT_COUNT:-4}
      - QUAKE_BOT_SKILL=${QUAKE_BOT_SKILL:-1}
      
      # Mod support
      - QUAKE_MOD=${QUAKE_MOD:-}
      
      # Debug settings
      - QUAKE_CONDEBUG=${QUAKE_CONDEBUG:-1}
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "netstat", "-an", "|", "grep", ":26000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Restart policy
    restart: unless-stopped
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
