name: Sync Upstream Source

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    name: Sync upstream to local upstream branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote and fetch
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add upstream https://github.com/Novum/vkQuake.git
          git tag -l | xargs -r git tag -d
          git fetch upstream --tags --force

      - name: Reset upstream branch and preserve workflows
        run: |
          # Save your workflows
          mkdir -p /tmp/my-workflows
          cp -r .github/workflows/* /tmp/my-workflows/ 2>/dev/null || true
          
          git checkout -B upstream upstream/master
          rm -rf .github/workflows
          mkdir -p .github/workflows
          cp -r /tmp/my-workflows/* .github/workflows/ 2>/dev/null || true
          
          git add .
          git commit -m "Sync upstream, preserve local workflows" || true
          git push origin upstream --force

      - name: Push all tags to origin
        run: |
          git push origin --tags --force

      - name: Sync tags (stripped version)
        run: |
          # Create a temporary directory to preserve your workflows
          mkdir -p /tmp/my-workflows
          cp -r .github/workflows/* /tmp/my-workflows/ 2>/dev/null || true
          
          for tag in $(git tag -l); do
            echo "Processing tag: $tag"
            git checkout -f $tag
            
            # Remove upstream workflows but keep your own
            rm -rf .github/workflows
            mkdir -p .github/workflows
            cp -r /tmp/my-workflows/* .github/workflows/ 2>/dev/null || true
            
            git add .
            git commit -m "Strip upstream workflows from $tag, keep local workflows" || true
            git tag -f $tag
          done
          
          # Return to main branch and restore workflows
          git checkout upstream
          rm -rf .github/workflows
          mkdir -p .github/workflows
          cp -r /tmp/my-workflows/* .github/workflows/ 2>/dev/null || true
          
          git push origin --tags --force
